version: "3"
services:
  db:
    image: mysql
    container_name: account-service-db
    restart: always
    environment:
      MYSQL_DATABASE: accountdb
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"