version: "3"
services:
  db:
    image: mysql
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: tripdb
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3311:3306"