version: "3"
services:
  db:
    image: mysql
    container_name: user-service-db
    restart: always
    environment:
      MYSQL_DATABASE: userdb
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3308:3306"