server:
  port: 8080


jwt:
  secret: secretito
  expiration: 3600 # Token expiration time in seconds

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: http://localhost:8002
              predicates:
                - Path=/users/**
            - id: stop-service
              uri: http://localhost:8086
              predicates:
                - Path=/stop/**
            - id: scooter-service
              uri: http://localhost:8081
              predicates:
                - Path=/scooter/**
            - id: report-service
              uri: http://localhost:8085
              predicates:
                - Path=/report/**
            - id: account-service
              uri: http://localhost:8001
              predicates:
                - Path=/account/**
            - id: trip-service
              uri: http://localhost:8084
              predicates:
                - Path=/trip/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG