version: "3"
services:
  db:
    image: mysql
    container_name: stop-service-db
    restart: always
    environment:
      MYSQL_DATABASE: stopdb
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3309:3306"